---
title: "Modelling Multivariate Bernoulli"
output: html_notebook
references:
  - id: teugels1
    title: Some representations of the multivariate Bernoulli and binomial distributions
    author: 
        - family: Teugels
          given: Jozef 
    container-title: Journal of Multivariate Analysis
    issued:
        year: 1990
        month: 8
  - id: dai1
    title: Multivariate Bernoulli distribution
    author: 
        - family: Dai
          given: Bin 
        - family: Ding
          given: Shiiin 
        - family: Wahba
          given: Grace 
    container-title: Bernoulli
    issued:
        year: 2013
        month: 1
---

# Motivation


This work is concerned with multivariate binary data, i.e. we have a dataset $X$ of $N$ observations of $D$ binary variables.

$X_{id} \sim \text{Bern}(\theta_{d})$

With $i = 1, \dots, N$ and $d = 1, \dots, D$ and $\theta_d$ is the Bernoulli probability parameter for variable $d$.

So far, this analysis has **assumed that the $D$ Bernoulli variables are independent**.

Of course, this is a large assumption that will fall apart for many datasets, particularly the genetics ones we are looking at.
In the continuous domain the [multivariate Normal distribution](https://en.wikipedia.org/wiki/Multivariate_normal_distribution) explicitly parameterises the correlation between the variables, however, there is no commonly used such method for the Bernoulli.

This notebook is motivated by the desire to find a way to explicitly model this correlation structure in order to more accurately represent the data generating process.

# Solutions

## Multi-variate distribution with correlation

The obvious solution is to use a multi-variate Bernoulli that includes the correlation structure. 
However, [this StackExchange post](https://stats.stackexchange.com/questions/279706/correlated-bernoulli-trials-multivariate-bernoulli-distribution) states that this is impossible for the situation where $D > 2$ due to lack of identifiability.

## Pairwise correlations

One solution is to identify a set of pairwise variables that we know have a non-zero correlation and want to explicitly model.

I.e. for 2 random Bernoulli variables $X$ and $Y$, $P_{ij} = Pr(X=i, Y=i)$.
Take the contingency matrix of all possible 4 results, which parameterises this distribution:

  - $P_{00} = a$
  - $P_{01} = b$
  - $P_{10} = c$
  - $P_{11} = d$
  
This can be reduced to three parameters:

  - $p_x = E(X) = Pr(X = 1) = 1 - q_x$
  - $p_y = E(Y) = Pr(Y = 1) = 1 - q_y$
  - $\mu_{xy} = E(XY)$
  
  
So that

  - $P_{00} = 1 - p_x - p_y + \mu_{xy}$
  - $P_{01} = p_x - \mu_{xy}$
  - $P_{10} = p_y - \mu_{xy}$
  - $P_{11} = \mu_{xy}$

So then the data can be modelled as comprising from a set of variables that are pairwise-correlated with a number of variables that aren't correlated with anything.

**How would the probability model look?**

## Multivariate Bernoulli revisited

@teugels1 generalises the notation in the previous section leading to a paramaterisation of a multi-variate Bernoulli distribution.
**However, for $D$ Bernoulli variables this distribution requires $2^{D}-1$ parameters**, which gets to be more than 1,000 for just $D=10$, this is untractable for genomic datasets where there are hundreds of variables!

@dai1

# Bibliography
