# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collapsed_gibbs_cpp <- function(df, initialK, nsamples, K, alpha, beta, gamma, burnin, debug) {
    .Call(`_bmmmcmc_collapsed_gibbs_cpp`, df, initialK, nsamples, K, alpha, beta, gamma, burnin, debug)
}

collapsed_gibbs_dp_cpp <- function(df, nsamples, alpha, beta, gamma, a, b, burnin, debug) {
    .Call(`_bmmmcmc_collapsed_gibbs_dp_cpp`, df, nsamples, alpha, beta, gamma, a, b, burnin, debug)
}

rdirichlet_cpp <- function(alpha_m) {
    .Call(`_bmmmcmc_rdirichlet_cpp`, alpha_m)
}

gibbs_cpp <- function(df, initialPi, initialTheta, nsamples, K, alpha, beta, gamma, burnin, debug) {
    .Call(`_bmmmcmc_gibbs_cpp`, df, initialPi, initialTheta, nsamples, K, alpha, beta, gamma, burnin, debug)
}

