# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allocation_cpp <- function(df, initialK, nsamples, maxK, alpha, beta, gamma, a, b, burnin, relabel, burnrelabel, debug) {
    .Call('_bmmmcmc_allocation_cpp', PACKAGE = 'bmmmcmc', df, initialK, nsamples, maxK, alpha, beta, gamma, a, b, burnin, relabel, burnrelabel, debug)
}

collapsed_gibbs_cpp <- function(df, initialK, nsamples, K, alpha, beta, gamma, a, b, burnin, relabel, burnrelabel, debug) {
    .Call('_bmmmcmc_collapsed_gibbs_cpp', PACKAGE = 'bmmmcmc', df, initialK, nsamples, K, alpha, beta, gamma, a, b, burnin, relabel, burnrelabel, debug)
}

collapsed_gibbs_dp_cpp <- function(df, nsamples, alpha, beta, gamma, a, b, burnin, relabel, burnrelabel, maxK, debug) {
    .Call('_bmmmcmc_collapsed_gibbs_dp_cpp', PACKAGE = 'bmmmcmc', df, nsamples, alpha, beta, gamma, a, b, burnin, relabel, burnrelabel, maxK, debug)
}

rdirichlet_cpp <- function(alpha_m) {
    .Call('_bmmmcmc_rdirichlet_cpp', PACKAGE = 'bmmmcmc', alpha_m)
}

gibbs_cpp <- function(df, initialPi, initialTheta, nsamples, K, alpha, beta, gamma, a, b, burnin, relabel, burnrelabel, debug) {
    .Call('_bmmmcmc_gibbs_cpp', PACKAGE = 'bmmmcmc', df, initialPi, initialTheta, nsamples, K, alpha, beta, gamma, a, b, burnin, relabel, burnrelabel, debug)
}

my_lpsolve <- function(x) {
    .Call('_bmmmcmc_my_lpsolve', PACKAGE = 'bmmmcmc', x)
}

my_stephens_batch <- function(p, debug) {
    .Call('_bmmmcmc_my_stephens_batch', PACKAGE = 'bmmmcmc', p, debug)
}

gibbs_stickbreaking_cpp <- function(df, initialPi, initialTheta, nsamples, maxK, alpha, beta, gamma, a, b, burnin, relabel, burnrelabel, debug) {
    .Call('_bmmmcmc_gibbs_stickbreaking_cpp', PACKAGE = 'bmmmcmc', df, initialPi, initialTheta, nsamples, maxK, alpha, beta, gamma, a, b, burnin, relabel, burnrelabel, debug)
}

